export { Hero } from "./Hero"
export { About } from "./About"
export { Objectives } from "./Objectives"
export { News } from "./News"
export { TrainingSession } from "./TrainingSession"
export { Outputs } from "./Outputs"
export { Partners } from "./Partners"
export { Impact } from "./Impact"
export { Contacts } from "./Contacts"
export { Footer } from "./Footer"

